### ISSUE TITLE
Components under '/library/new-component/' can not consume  

### ISSUE THREAD

**Issue by e06widu** [aguacongas/generator-angular-cli-library#8]
I created a library and added new component under /library/new-component/ and added it to library.modules.ts and index.ts.
But it can not consume from another project.
But all the components under library folder can consume.

Can any one help me please.

**Comment by aguacongas** [comment]
Did you export it in your module :   
```typescript
@NgModule({
  imports: [
    CommonModule
  ],
  exports: [
    NewComponent
  ],
  declarations: [ NewComponent ],
  providers: []
})
export class LibraryModule { }

```

**Comment by e06widu** [comment]
Yes I did but it doesn't identify by my cli project. That is the issue I'm facing. 
All the components inside Library/Library folder are getting identify. But component inside Library/components folder does not identify.

**Comment by aguacongas** [comment]
`exports: [],` !! it's empty, that cannot works. You should have : `exports: [UsTabComponent, LibraryComponent, LibraryPipe, LibraryDirective, UsInputComponent],`  
Look at, just after the declarations in your NgModule decorator

**Comment by e06widu** [comment]
Thank You. It works. :)
